#frontend deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      name: frontend-pod
      labels:
        app: expense-tracker
    spec:
      containers:
       - name: frontend-pod
         image: image-registry.openshift-image-registry.svc:5000/amisha-jenkins/expense-tracker-frontend

         ports:
          - containerPort: 3000
         env:
            - name: REACT_APP_API_BASE_URL
              value: http://backend-route-amisha-poc.edge-dev-410-915b3b336cabec458a7c7ec2aa7c625f-0000.us-south.containers.appdomain.cloud

---
#frontend-service
kind: Service
apiVersion: v1
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 3000
      port: 3000
      Selector: 
        app: expense-tracker
        
---
#frontend-service
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: frontend-route
  namespace: amisha-jenkins
  labels:
    app: expense-tracker
spec:
  to:
    kind: Service
    name: frontend-service
  port:
    targetPort: 3000
