#backend deployment
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  labels:
    app: expense-tracker
spec:
   replicas: 1
   selector:
     matchLabels:
      app: expense-tracker
   template:
     metadata:
        name: backend-pod
        labels:
          app: expense-tracker
     spec: 
       containers:
        - name: backend-pod 
          image: image-registry.openshift-image-registry.svc:5000/amisha-jenkins/expense-tracker-backend:latest
          ports:
           - containerPort: 5000
          env: 
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: DB_URL
              value: mongodb-service.amisha-poc.svc.cluster.local:27017/mydatabase
            - name: NODE_ENV
              value: production  
            - name: PORT
              value: '5000'
            - name: BASE_URL
              value:  http://frontend-route-amisha-poc.edge-dev-410-915b3b336cabec458a7c7ec2aa7c625f-0000.us-south.containers.appdomain.cloud

---
#backend-service
kind: Service 
apiVersion: v1 
metadata: 
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 5000
      port: 5000
      selector:
        app: expense-tracker
--
#backend-route
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: backend-route
  namespace: amisha-jenkins
  labels:
    app: expense-tracker
spec:
  to:
    kind: Service
    name: backend-service
  port:
    targetPort: 5000


